version: 0.2

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - >
        aws cloudformation package
        --s3-bucket testing-bucket-agupta
        --template-file .aws-sam/build/template.yaml
        --output-template-file packaged.yaml

artifacts:
     files:
      - packaged.yaml
