AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: wave-cognito-lambdas
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
Resources:
  MigrateUserTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testing-bucket-agupta/3886498f42f03ba7414e65c400d55445
      Handler: userMigration.handler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
        - userMigration.ts
  CustomMessageTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://testing-bucket-agupta/90cad6c49966f1ffb9ef1c5ad60caecb
      Handler: customMessage.handler
      Runtime: nodejs14.x
      Architectures:
      - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
        - customMessage.ts
